DROP TABLE IF EXISTS sqldados.iprdConferencia;
CREATE TABLE sqldados.iprdConferencia (
  `invno` INT(10)     NOT NULL DEFAULT '0',
  `prdno` CHAR(16)    NOT NULL DEFAULT '',
  `grade` CHAR(8)     NOT NULL DEFAULT '',
  `qtty`  int(10)     NOT NULL DEFAULT '0',
  `fob`   bigint(15)  NOT NULL DEFAULT '0',
  `s27`   smallint(5) NOT NULL DEFAULT '0',
  PRIMARY KEY (invno, prdno, grade)
);

DROP TABLE IF EXISTS sqldados.invConferencia;
CREATE TABLE sqldados.invConferencia (
  `invno`    INT(10)     NOT NULL DEFAULT '0',
  `storeno`  smallint(5) NOT NULL DEFAULT '0',
  `nfname`   char(32)    NOT NULL DEFAULT '',
  `invse`    char(4)     NOT NULL DEFAULT '',
  issue_date INT(11)     NOT NULL DEFAULT 0,
  nfekey     char(60)    NOT NULL DEFAULT '',
  PRIMARY KEY (invno),
  UNIQUE (nfekey)
);


SHOW CREATE TABLE sqldados.iprd;

CREATE TABLE `iprd` (
  `invno`             int(10)     NOT NULL DEFAULT '0',
  `qtty`              int(10)     NOT NULL DEFAULT '0',
  `fob`               bigint(15)  NOT NULL DEFAULT '0',
  `cost`              bigint(15)  NOT NULL DEFAULT '0',
  `date`              int(10)     NOT NULL DEFAULT '0',
  `ipi`               int(10)     NOT NULL DEFAULT '0',
  `auxLong1`          int(10)     NOT NULL DEFAULT '0',
  `auxLong2`          int(10)     NOT NULL DEFAULT '0',
  `frete`             int(10)     NOT NULL DEFAULT '0',
  `seguro`            int(10)     NOT NULL DEFAULT '0',
  `despesas`          int(10)     NOT NULL DEFAULT '0',
  `freteIpi`          int(10)     NOT NULL DEFAULT '0',
  `qttyRessar`        int(10)     NOT NULL DEFAULT '0',
  `baseIcmsSubst`     bigint(15)  NOT NULL DEFAULT '0',
  `icmsSubst`         bigint(15)  NOT NULL DEFAULT '0',
  `icms`              bigint(15)  NOT NULL DEFAULT '0',
  `discount`          bigint(15)  NOT NULL DEFAULT '0',
  `fob4`              bigint(15)  NOT NULL DEFAULT '0',
  `cost4`             bigint(15)  NOT NULL DEFAULT '0',
  `icmsAliq`          int(10)     NOT NULL DEFAULT '0',
  `cfop`              int(10)     NOT NULL DEFAULT '0',
  `auxLong3`          int(10)     NOT NULL DEFAULT '0',
  `auxLong4`          int(10)     NOT NULL DEFAULT '0',
  `auxLong5`          int(10)     NOT NULL DEFAULT '0',
  `auxMy1`            bigint(15)  NOT NULL DEFAULT '0',
  `auxMy2`            bigint(15)  NOT NULL DEFAULT '0',
  `auxMy3`            bigint(15)  NOT NULL DEFAULT '0',
  `baseIcms`          bigint(15)  NOT NULL,
  `baseIpi`           bigint(15)  NOT NULL,
  `ipiAmt`            bigint(15)  NOT NULL,
  `reducaoBaseIcms`   bigint(15)  NOT NULL,
  `amtCredIcmsSN`     bigint(15)  NOT NULL DEFAULT '0',
  `amtFcpSt`          bigint(15)  NOT NULL DEFAULT '0',
  `amtFcpStRet`       bigint(15)  NOT NULL DEFAULT '0',
  `amtFcpUfDest`      bigint(15)  NOT NULL DEFAULT '0',
  `amtIcmsDeson`      bigint(15)  NOT NULL DEFAULT '0',
  `amtIcmsDifer`      bigint(15)  NOT NULL DEFAULT '0',
  `amtIcmsEfet`       bigint(15)  NOT NULL DEFAULT '0',
  `amtIof`            bigint(15)  NOT NULL DEFAULT '0',
  `amtIssQN`          bigint(15)  NOT NULL DEFAULT '0',
  `amtIssRet`         bigint(15)  NOT NULL DEFAULT '0',
  `amtSubstDest`      bigint(15)  NOT NULL DEFAULT '0',
  `amtSubstRetRemet`  bigint(15)  NOT NULL DEFAULT '0',
  `baseFcp`           bigint(15)  NOT NULL DEFAULT '0',
  `baseFcpSt`         bigint(15)  NOT NULL DEFAULT '0',
  `baseFcpStRet`      bigint(15)  NOT NULL DEFAULT '0',
  `baseFcpUfDest`     bigint(15)  NOT NULL DEFAULT '0',
  `baseIcmsEfet`      bigint(15)  NOT NULL DEFAULT '0',
  `baseII`            bigint(15)  NOT NULL DEFAULT '0',
  `baseIssQN`         bigint(15)  NOT NULL DEFAULT '0',
  `baseSubstDest`     bigint(15)  NOT NULL DEFAULT '0',
  `baseSubstRetRemet` bigint(15)  NOT NULL DEFAULT '0',
  `deducoes`          bigint(15)  NOT NULL DEFAULT '0',
  `outrasRet`         bigint(15)  NOT NULL DEFAULT '0',
  `lucroTributado`    int(10)     NOT NULL,
  `aliqFcp`           int(10)     NOT NULL DEFAULT '0',
  `aliqFcpSt`         int(10)     NOT NULL DEFAULT '0',
  `aliqFcpStRet`      int(10)     NOT NULL DEFAULT '0',
  `aliqFcpUfDest`     int(10)     NOT NULL DEFAULT '0',
  `aliqIcmsDifer`     int(10)     NOT NULL DEFAULT '0',
  `aliqIcmsEfet`      int(10)     NOT NULL DEFAULT '0',
  `aliqIcmsInter`     int(10)     NOT NULL DEFAULT '0',
  `aliqIcmsPart`      int(10)     NOT NULL DEFAULT '0',
  `aliqIcmsUfDest`    int(10)     NOT NULL DEFAULT '0',
  `aliqIssQN`         int(10)     NOT NULL DEFAULT '0',
  `motIcmsDeson`      int(10)     NOT NULL DEFAULT '0',
  `percBaseOper`      int(10)     NOT NULL DEFAULT '0',
  `percCredSN`        int(10)     NOT NULL DEFAULT '0',
  `percRedIcmsEfet`   int(10)     NOT NULL DEFAULT '0',
  `percRedIcmsSt`     int(10)     NOT NULL DEFAULT '0',
  `dfob`              double      NOT NULL DEFAULT '0',
  `l1`                int(10)     NOT NULL,
  `l2`                int(10)     NOT NULL,
  `l3`                int(10)     NOT NULL,
  `l4`                int(10)     NOT NULL,
  `l5`                int(10)     NOT NULL,
  `l6`                int(10)     NOT NULL,
  `l7`                int(10)     NOT NULL,
  `l8`                int(10)     NOT NULL,
  `l9`                int(10)     NOT NULL DEFAULT '0',
  `l10`               int(10)     NOT NULL DEFAULT '0',
  `l11`               int(10)     NOT NULL DEFAULT '0',
  `l12`               int(10)     NOT NULL DEFAULT '0',
  `l13`               int(10)     NOT NULL DEFAULT '0',
  `l14`               int(10)     NOT NULL DEFAULT '0',
  `l15`               int(10)     NOT NULL DEFAULT '0',
  `l16`               int(10)     NOT NULL DEFAULT '0',
  `l17`               int(10)     NOT NULL DEFAULT '0',
  `l18`               int(10)     NOT NULL DEFAULT '0',
  `l19`               int(10)     NOT NULL DEFAULT '0',
  `l20`               int(10)     NOT NULL DEFAULT '0',
  `l21`               int(10)     NOT NULL DEFAULT '0',
  `l22`               int(10)     NOT NULL DEFAULT '0',
  `l23`               int(10)     NOT NULL DEFAULT '0',
  `l24`               int(10)     NOT NULL DEFAULT '0',
  `l25`               int(10)     NOT NULL DEFAULT '0',
  `l26`               int(10)     NOT NULL DEFAULT '0',
  `l27`               int(10)     NOT NULL DEFAULT '0',
  `l28`               int(10)     NOT NULL DEFAULT '0',
  `m1`                bigint(15)  NOT NULL,
  `m2`                bigint(15)  NOT NULL,
  `m3`                bigint(15)  NOT NULL,
  `m4`                bigint(15)  NOT NULL,
  `m5`                bigint(15)  NOT NULL,
  `m6`                bigint(15)  NOT NULL,
  `m7`                bigint(15)  NOT NULL,
  `m8`                bigint(15)  NOT NULL,
  `m9`                bigint(15)  NOT NULL DEFAULT '0',
  `m10`               bigint(15)  NOT NULL DEFAULT '0',
  `m11`               bigint(15)  NOT NULL DEFAULT '0',
  `m12`               bigint(15)  NOT NULL DEFAULT '0',
  `m13`               bigint(15)  NOT NULL DEFAULT '0',
  `m14`               bigint(15)  NOT NULL DEFAULT '0',
  `m15`               bigint(15)  NOT NULL DEFAULT '0',
  `m16`               bigint(15)  NOT NULL DEFAULT '0',
  `m17`               bigint(15)  NOT NULL DEFAULT '0',
  `m18`               bigint(15)  NOT NULL DEFAULT '0',
  `m19`               bigint(15)  NOT NULL DEFAULT '0',
  `m20`               bigint(15)  NOT NULL DEFAULT '0',
  `m21`               bigint(15)  NOT NULL DEFAULT '0',
  `m22`               bigint(15)  NOT NULL DEFAULT '0',
  `m23`               bigint(15)  NOT NULL DEFAULT '0',
  `m24`               bigint(15)  NOT NULL DEFAULT '0',
  `m25`               bigint(15)  NOT NULL DEFAULT '0',
  `m26`               bigint(15)  NOT NULL DEFAULT '0',
  `m27`               bigint(15)  NOT NULL DEFAULT '0',
  `m28`               bigint(15)  NOT NULL DEFAULT '0',
  `d1`                double      NOT NULL DEFAULT '0',
  `d2`                double      NOT NULL DEFAULT '0',
  `d3`                double      NOT NULL DEFAULT '0',
  `d4`                double      NOT NULL DEFAULT '0',
  `d5`                double      NOT NULL DEFAULT '0',
  `d6`                double      NOT NULL DEFAULT '0',
  `d7`                double      NOT NULL DEFAULT '0',
  `d8`                double      NOT NULL DEFAULT '0',
  `d9`                double      NOT NULL DEFAULT '0',
  `d10`               double      NOT NULL DEFAULT '0',
  `d11`               double      NOT NULL DEFAULT '0',
  `d12`               double      NOT NULL DEFAULT '0',
  `d13`               double      NOT NULL DEFAULT '0',
  `d14`               double      NOT NULL DEFAULT '0',
  `d15`               double      NOT NULL DEFAULT '0',
  `d16`               double      NOT NULL DEFAULT '0',
  `d17`               double      NOT NULL DEFAULT '0',
  `d18`               double      NOT NULL DEFAULT '0',
  `d19`               double      NOT NULL DEFAULT '0',
  `d20`               double      NOT NULL DEFAULT '0',
  `storeno`           smallint(5) NOT NULL DEFAULT '0',
  `bits`              smallint(5) NOT NULL DEFAULT '0',
  `auxShort1`         smallint(5) NOT NULL DEFAULT '0',
  `auxShort2`         smallint(5) NOT NULL DEFAULT '0',
  `taxtype`           smallint(5) NOT NULL DEFAULT '0',
  `auxShort3`         smallint(5) NOT NULL DEFAULT '0',
  `auxShort4`         smallint(5) NOT NULL DEFAULT '0',
  `auxShort5`         smallint(5) NOT NULL DEFAULT '0',
  `seqno`             smallint(5) NOT NULL,
  `bits2`             smallint(5) NOT NULL,
  `bits3`             smallint(5) NOT NULL,
  `bits4`             smallint(5) NOT NULL,
  `s1`                smallint(5) NOT NULL,
  `s2`                smallint(5) NOT NULL,
  `s3`                smallint(5) NOT NULL,
  `s4`                smallint(5) NOT NULL,
  `s5`                smallint(5) NOT NULL,
  `s6`                smallint(5) NOT NULL,
  `s7`                smallint(5) NOT NULL,
  `s8`                smallint(5) NOT NULL,
  `s9`                smallint(5) NOT NULL DEFAULT '0',
  `s10`               smallint(5) NOT NULL DEFAULT '0',
  `s11`               smallint(5) NOT NULL DEFAULT '0',
  `s12`               smallint(5) NOT NULL DEFAULT '0',
  `s13`               smallint(5) NOT NULL DEFAULT '0',
  `s14`               smallint(5) NOT NULL DEFAULT '0',
  `s15`               smallint(5) NOT NULL DEFAULT '0',
  `s16`               smallint(5) NOT NULL DEFAULT '0',
  `s17`               smallint(5) NOT NULL DEFAULT '0',
  `s18`               smallint(5) NOT NULL DEFAULT '0',
  `s19`               smallint(5) NOT NULL DEFAULT '0',
  `s20`               smallint(5) NOT NULL DEFAULT '0',
  `s21`               smallint(5) NOT NULL DEFAULT '0',
  `s22`               smallint(5) NOT NULL DEFAULT '0',
  `s23`               smallint(5) NOT NULL DEFAULT '0',
  `s24`               smallint(5) NOT NULL DEFAULT '0',
  `s25`               smallint(5) NOT NULL DEFAULT '0',
  `s26`               smallint(5) NOT NULL DEFAULT '0',
  `s27`               smallint(5) NOT NULL DEFAULT '0',
  `s28`               smallint(5) NOT NULL DEFAULT '0',
  `prdno`             char(16)    NOT NULL DEFAULT '',
  `grade`             char(8)     NOT NULL DEFAULT '',
  `auxChar`           char(20)    NOT NULL DEFAULT '',
  `auxChar2`          char(20)    NOT NULL DEFAULT '',
  `cstIcms`           char(4)     NOT NULL,
  `cstIpi`            char(4)     NOT NULL,
  `c1`                char(40)    NOT NULL,
  `c2`                char(40)    NOT NULL DEFAULT '',
  `c3`                char(40)    NOT NULL DEFAULT '',
  `c4`                char(40)    NOT NULL DEFAULT '',
  `c5`                char(40)    NOT NULL DEFAULT '',
  `c6`                char(40)    NOT NULL DEFAULT '',
  `c7`                char(40)    NOT NULL DEFAULT '',
  `c8`                char(40)    NOT NULL DEFAULT '',
  `c9`                char(40)    NOT NULL DEFAULT '',
  `c10`               char(40)    NOT NULL DEFAULT '',
  PRIMARY KEY (`invno`, `prdno`, `grade`, `fob`),
  KEY `i2`(`prdno`, `grade`, `date`, `storeno`),
  KEY `i3`(`prdno`, `grade`, `storeno`, `date`),
  KEY `i4`(`storeno`, `prdno`, `date`),
  KEY `i5`(`prdno`, `date`, `storeno`, `grade`),
  KEY `i6`(`storeno`, `date`),
  KEY `i7`(`invno`, `s1`, `prdno`, `grade`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = latin1;

SHOW CREATE TABLE sqldados.inv;

CREATE TABLE `inv` (
  `invno`        int(11)     NOT NULL AUTO_INCREMENT,
  `vendno`       int(10)     NOT NULL,
  `ordno`        int(10)     NOT NULL DEFAULT '0',
  `xfrno`        int(10)     NOT NULL DEFAULT '0',
  `issue_date`   int(10)     NOT NULL DEFAULT '0',
  `date`         int(10)     NOT NULL DEFAULT '0',
  `comp_date`    int(10)     NOT NULL DEFAULT '0',
  `ipi`          bigint(15)  NOT NULL DEFAULT '0',
  `icm`          bigint(15)  NOT NULL DEFAULT '0',
  `freight`      bigint(15)  NOT NULL DEFAULT '0',
  `netamt`       bigint(15)  NOT NULL DEFAULT '0',
  `grossamt`     bigint(15)  NOT NULL DEFAULT '0',
  `subst_trib`   bigint(15)  NOT NULL DEFAULT '0',
  `discount`     bigint(15)  NOT NULL DEFAULT '0',
  `prdamt`       bigint(15)  NOT NULL DEFAULT '0',
  `despesas`     bigint(15)  NOT NULL DEFAULT '0',
  `base_ipi`     bigint(15)  NOT NULL DEFAULT '0',
  `aliq`         int(10)     NOT NULL DEFAULT '0',
  `cfo`          int(10)     NOT NULL DEFAULT '0',
  `nfNfno`       int(10)     NOT NULL DEFAULT '0',
  `auxLong1`     int(10)     NOT NULL DEFAULT '0',
  `auxLong2`     int(10)     NOT NULL DEFAULT '0',
  `auxMoney1`    bigint(15)  NOT NULL DEFAULT '0',
  `auxMoney2`    bigint(15)  NOT NULL DEFAULT '0',
  `dataSaida`    int(10)     NOT NULL DEFAULT '0',
  `amtServicos`  bigint(15)  NOT NULL DEFAULT '0',
  `amtIRRF`      bigint(15)  NOT NULL DEFAULT '0',
  `amtINSS`      bigint(15)  NOT NULL DEFAULT '0',
  `amtISS`       bigint(15)  NOT NULL DEFAULT '0',
  `auxMoney3`    bigint(15)  NOT NULL DEFAULT '0',
  `auxMoney4`    bigint(15)  NOT NULL DEFAULT '0',
  `auxMoney5`    bigint(15)  NOT NULL DEFAULT '0',
  `auxLong3`     int(10)     NOT NULL DEFAULT '0',
  `auxLong4`     int(10)     NOT NULL DEFAULT '0',
  `auxLong5`     int(10)     NOT NULL DEFAULT '0',
  `auxLong6`     int(10)     NOT NULL DEFAULT '0',
  `auxLong7`     int(10)     NOT NULL DEFAULT '0',
  `auxLong8`     int(10)     NOT NULL DEFAULT '0',
  `auxLong9`     int(10)     NOT NULL DEFAULT '0',
  `auxLong10`    int(10)     NOT NULL DEFAULT '0',
  `auxLong11`    int(10)     NOT NULL DEFAULT '0',
  `auxLong12`    int(10)     NOT NULL DEFAULT '0',
  `auxMoney6`    bigint(15)  NOT NULL DEFAULT '0',
  `auxMoney7`    bigint(15)  NOT NULL DEFAULT '0',
  `auxMoney8`    bigint(15)  NOT NULL DEFAULT '0',
  `auxMoney9`    bigint(15)  NOT NULL DEFAULT '0',
  `auxMoney10`   bigint(15)  NOT NULL DEFAULT '0',
  `auxMoney11`   bigint(15)  NOT NULL DEFAULT '0',
  `auxMoney12`   bigint(15)  NOT NULL DEFAULT '0',
  `auxMoney13`   bigint(15)  NOT NULL DEFAULT '0',
  `icmsUfRemet`  bigint(15)  NOT NULL DEFAULT '0',
  `fcp`          bigint(15)  NOT NULL DEFAULT '0',
  `fcpSt`        bigint(15)  NOT NULL DEFAULT '0',
  `fcpStRet`     bigint(15)  NOT NULL DEFAULT '0',
  `servico`      bigint(15)  NOT NULL DEFAULT '0',
  `baseIss`      bigint(15)  NOT NULL DEFAULT '0',
  `deducoes`     bigint(15)  NOT NULL DEFAULT '0',
  `retencoes`    bigint(15)  NOT NULL DEFAULT '0',
  `impImport`    bigint(15)  NOT NULL DEFAULT '0',
  `issRetido`    bigint(15)  NOT NULL DEFAULT '0',
  `l1`           int(10)     NOT NULL,
  `l2`           int(10)     NOT NULL,
  `l3`           int(10)     NOT NULL,
  `l4`           int(10)     NOT NULL,
  `l5`           int(10)     NOT NULL,
  `l6`           int(10)     NOT NULL,
  `l7`           int(10)     NOT NULL,
  `l8`           int(10)     NOT NULL,
  `l9`           int(10)     NOT NULL DEFAULT '0',
  `l10`          int(10)     NOT NULL DEFAULT '0',
  `l11`          int(10)     NOT NULL DEFAULT '0',
  `l12`          int(10)     NOT NULL DEFAULT '0',
  `l13`          int(10)     NOT NULL DEFAULT '0',
  `l14`          int(10)     NOT NULL DEFAULT '0',
  `l15`          int(10)     NOT NULL DEFAULT '0',
  `l16`          int(10)     NOT NULL DEFAULT '0',
  `l17`          int(10)     NOT NULL DEFAULT '0',
  `l18`          int(10)     NOT NULL DEFAULT '0',
  `l19`          int(10)     NOT NULL DEFAULT '0',
  `l20`          int(10)     NOT NULL DEFAULT '0',
  `l21`          int(10)     NOT NULL DEFAULT '0',
  `l22`          int(10)     NOT NULL DEFAULT '0',
  `l23`          int(10)     NOT NULL DEFAULT '0',
  `l24`          int(10)     NOT NULL DEFAULT '0',
  `l25`          int(10)     NOT NULL DEFAULT '0',
  `l26`          int(10)     NOT NULL DEFAULT '0',
  `l27`          int(10)     NOT NULL DEFAULT '0',
  `l28`          int(10)     NOT NULL DEFAULT '0',
  `m1`           bigint(15)  NOT NULL,
  `m2`           bigint(15)  NOT NULL,
  `m3`           bigint(15)  NOT NULL,
  `m4`           bigint(15)  NOT NULL,
  `m5`           bigint(15)  NOT NULL,
  `m6`           bigint(15)  NOT NULL,
  `m7`           bigint(15)  NOT NULL,
  `m8`           bigint(15)  NOT NULL,
  `m9`           bigint(15)  NOT NULL DEFAULT '0',
  `m10`          bigint(15)  NOT NULL DEFAULT '0',
  `m11`          bigint(15)  NOT NULL DEFAULT '0',
  `m12`          bigint(15)  NOT NULL DEFAULT '0',
  `m13`          bigint(15)  NOT NULL DEFAULT '0',
  `m14`          bigint(15)  NOT NULL DEFAULT '0',
  `m15`          bigint(15)  NOT NULL DEFAULT '0',
  `m16`          bigint(15)  NOT NULL DEFAULT '0',
  `m17`          bigint(15)  NOT NULL DEFAULT '0',
  `m18`          bigint(15)  NOT NULL DEFAULT '0',
  `m19`          bigint(15)  NOT NULL DEFAULT '0',
  `m20`          bigint(15)  NOT NULL DEFAULT '0',
  `m21`          bigint(15)  NOT NULL DEFAULT '0',
  `m22`          bigint(15)  NOT NULL DEFAULT '0',
  `m23`          bigint(15)  NOT NULL DEFAULT '0',
  `m24`          bigint(15)  NOT NULL DEFAULT '0',
  `m25`          bigint(15)  NOT NULL DEFAULT '0',
  `m26`          bigint(15)  NOT NULL DEFAULT '0',
  `m27`          bigint(15)  NOT NULL DEFAULT '0',
  `m28`          bigint(15)  NOT NULL DEFAULT '0',
  `weight`       double               DEFAULT NULL,
  `carrno`       smallint(5) NOT NULL DEFAULT '0',
  `packages`     smallint(5) NOT NULL DEFAULT '0',
  `storeno`      smallint(5) NOT NULL DEFAULT '0',
  `indxno`       smallint(5) NOT NULL DEFAULT '0',
  `book_bits`    smallint(5) NOT NULL DEFAULT '0',
  `type`         smallint(5) NOT NULL DEFAULT '0',
  `usernoFirst`  smallint(5) NOT NULL DEFAULT '0',
  `usernoLast`   smallint(5) NOT NULL DEFAULT '0',
  `nfStoreno`    smallint(5) NOT NULL DEFAULT '0',
  `bits`         smallint(5) NOT NULL DEFAULT '0',
  `padbyte`      smallint(5) NOT NULL DEFAULT '0',
  `auxShort1`    smallint(5) NOT NULL DEFAULT '0',
  `auxShort2`    smallint(5) NOT NULL DEFAULT '0',
  `auxShort3`    smallint(5) NOT NULL DEFAULT '0',
  `auxShort4`    smallint(5) NOT NULL DEFAULT '0',
  `auxShort5`    smallint(5) NOT NULL DEFAULT '0',
  `auxShort6`    smallint(5) NOT NULL DEFAULT '0',
  `auxShort7`    smallint(5) NOT NULL DEFAULT '0',
  `auxShort8`    smallint(5) NOT NULL DEFAULT '0',
  `auxShort9`    smallint(5) NOT NULL DEFAULT '0',
  `auxShort10`   smallint(5) NOT NULL DEFAULT '0',
  `auxShort11`   smallint(5) NOT NULL DEFAULT '0',
  `auxShort12`   smallint(5) NOT NULL DEFAULT '0',
  `auxShort13`   smallint(5) NOT NULL DEFAULT '0',
  `auxShort14`   smallint(5) NOT NULL DEFAULT '0',
  `bits2`        smallint(5) NOT NULL,
  `bits3`        smallint(5) NOT NULL,
  `bits4`        smallint(5) NOT NULL,
  `bits5`        smallint(5) NOT NULL DEFAULT '0',
  `s1`           smallint(5) NOT NULL,
  `s2`           smallint(5) NOT NULL,
  `s3`           smallint(5) NOT NULL,
  `s4`           smallint(5) NOT NULL,
  `s5`           smallint(5) NOT NULL,
  `s6`           smallint(5) NOT NULL,
  `s7`           smallint(5) NOT NULL,
  `s8`           smallint(5) NOT NULL,
  `s9`           smallint(5) NOT NULL DEFAULT '0',
  `s10`          smallint(5) NOT NULL DEFAULT '0',
  `s11`          smallint(5) NOT NULL DEFAULT '0',
  `s12`          smallint(5) NOT NULL DEFAULT '0',
  `s13`          smallint(5) NOT NULL DEFAULT '0',
  `s14`          smallint(5) NOT NULL DEFAULT '0',
  `s15`          smallint(5) NOT NULL DEFAULT '0',
  `s16`          smallint(5) NOT NULL DEFAULT '0',
  `s17`          smallint(5) NOT NULL DEFAULT '0',
  `s18`          smallint(5) NOT NULL DEFAULT '0',
  `s19`          smallint(5) NOT NULL DEFAULT '0',
  `s20`          smallint(5) NOT NULL DEFAULT '0',
  `s21`          smallint(5) NOT NULL DEFAULT '0',
  `s22`          smallint(5) NOT NULL DEFAULT '0',
  `s23`          smallint(5) NOT NULL DEFAULT '0',
  `s24`          smallint(5) NOT NULL DEFAULT '0',
  `s25`          smallint(5) NOT NULL DEFAULT '0',
  `s26`          smallint(5) NOT NULL DEFAULT '0',
  `s27`          smallint(5) NOT NULL DEFAULT '0',
  `s28`          smallint(5) NOT NULL DEFAULT '0',
  `nfname`       char(32)    NOT NULL DEFAULT '',
  `invse`        char(4)     NOT NULL DEFAULT '',
  `account`      char(16)    NOT NULL DEFAULT '',
  `remarks`      char(80)    NOT NULL DEFAULT '',
  `contaCredito` char(16)    NOT NULL DEFAULT '',
  `contaDebito`  char(16)    NOT NULL DEFAULT '',
  `nfNfse`       char(2)     NOT NULL DEFAULT '',
  `auxStr1`      char(20)    NOT NULL DEFAULT '',
  `auxStr2`      char(20)    NOT NULL DEFAULT '',
  `auxStr3`      char(20)    NOT NULL DEFAULT '',
  `auxStr4`      char(20)    NOT NULL DEFAULT '',
  `auxStr5`      char(20)    NOT NULL DEFAULT '',
  `auxStr6`      char(20)    NOT NULL DEFAULT '',
  `c1`           char(40)    NOT NULL,
  `c2`           char(40)    NOT NULL,
  `c3`           char(40)    NOT NULL DEFAULT '',
  `c4`           char(40)    NOT NULL DEFAULT '',
  `c5`           char(40)    NOT NULL DEFAULT '',
  `c6`           char(40)    NOT NULL DEFAULT '',
  `c7`           char(40)    NOT NULL DEFAULT '',
  `c8`           char(40)    NOT NULL DEFAULT '',
  `c9`           char(40)    NOT NULL DEFAULT '',
  `c10`          char(40)    NOT NULL DEFAULT '',
  PRIMARY KEY (`invno`),
  KEY `i3`(`account`),
  KEY `i4`(`carrno`),
  KEY `i5`(`ordno`),
  KEY `i6`(`storeno`, `invse`, `date`),
  KEY `i7`(`storeno`, `date`),
  KEY `i8`(`storeno`, `cfo`, `date`),
  KEY `i9`(`storeno`, `comp_date`),
  KEY `i10`(`storeno`, `nfname`, `invse`),
  KEY `i11`(`storeno`, `invno`),
  KEY `i12`(`auxLong7`, `nfname`, `invse`),
  KEY `i13`(`vendno`, `date`),
  KEY `i14`(`auxShort14`),
  KEY `i15`(`storeno`, `vendno`),
  KEY `i16`(`auxShort1`, `auxShort2`, `auxLong1`),
  KEY `i17`(`nfNfno`, `nfStoreno`, `nfNfse`),
  KEY `i18`(`auxLong3`),
  KEY `i19`(`storeno`, `account`),
  KEY `i20`(`l6`, `invno`),
  KEY `i21`(`storeno`, `vendno`, `nfname`),
  KEY `i22`(`storeno`, `vendno`, `date`),
  KEY `i23`(`l8`),
  KEY `i2`(`vendno`, `nfname`, `invse`, `invno`),
  KEY `e1`(`invno`, `storeno`, `type`),
  KEY `i24`(`vendno`, `issue_date`)
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 856034
  DEFAULT CHARSET = latin1;



SELECT N.storeno                                          AS loja,
       X.invno                                            AS ni,
       CAST(CONCAT(N.nfname, '/', N.invse) AS CHAR)       AS nota,
       CAST(TRIM(P.no) AS CHAR)                           AS codigo,
       IFNULL(X.grade, '')                                AS grade,
       TRIM(IFNULL(B.barcode, P.barcode))                 AS barcode,
       TRIM(MID(P.name, 1, 37))                           AS descricao,
       P.mfno                                             AS vendno,
       IFNULL(F.auxChar1, '')                             AS fornecedor,
       P.typeno                                           AS typeno,
       IFNULL(T.name, '')                                 AS typeName,
       CAST(LPAD(P.clno, 6, '0') AS CHAR)                 AS clno,
       IFNULL(cl.name, '')                                AS clname,
       P.m6                                               AS altura,
       P.m4                                               AS comprimento,
       P.m5                                               AS largura,
       P.sp / 100                                         AS precoCheio,
       IFNULL(S.ncm, '')                                  AS ncm,
       X.qtty / 1000                                      AS quantidade,
       X.fob / 100                                        AS preco,
       (X.qtty / 1000) * (X.fob / 100)                    AS total,
       X.s27                                              AS marca,
       CAST(MID(IFNULL(L.localizacao, ''), 1, 4) AS CHAR) AS localizacao
FROM sqldados.prd                     AS P
  INNER JOIN sqldados.iprdConferencia AS X
	       ON P.no = X.prdno
  INNER JOIN sqldados.invConferencia  AS N
	       USING (nfekey)
  LEFT JOIN  sqldados.prdbar          AS B
	       ON P.no = B.prdno AND B.grade = X.grade
  LEFT JOIN  sqldados.prdloc          AS L
	       ON L.prdno = P.no AND L.storeno = 4
  LEFT JOIN  sqldados.vend            AS F
	       ON F.no = P.mfno
  LEFT JOIN  sqldados.type            AS T
	       ON T.no = P.typeno
  LEFT JOIN  sqldados.cl
	       ON cl.no = P.clno
  LEFT JOIN  sqldados.spedprd         AS S
	       ON P.no = S.prdno
WHERE X.invno = :ni
  AND (X.s27 = :marca OR :marca = 0)
GROUP BY codigo, grade

