DROP TABLE IF EXISTS sqldados.iprdConferencia;
CREATE TABLE sqldados.iprdConferencia
(
    `invno` INT(10)     NOT NULL DEFAULT '0',
    `prdno` CHAR(16) NOT NULL DEFAULT '',
    `grade` CHAR(8)  NOT NULL DEFAULT '',
    `qtty`  INT(10)     NOT NULL DEFAULT '0',
    `fob`   BIGINT(15)  NOT NULL DEFAULT '0',
    `s27`   SMALLINT(5) NOT NULL DEFAULT '0',
    PRIMARY KEY (invno, prdno, grade)
);

DROP TABLE IF EXISTS sqldados.invConferencia;
CREATE TABLE sqldados.invConferencia
(
    `invno`    INT(10)     NOT NULL DEFAULT '0',
    `storeno`  SMALLINT(5) NOT NULL DEFAULT '0',
    `nfname`   CHAR(32) NOT NULL DEFAULT '',
    `invse`    CHAR(4)  NOT NULL DEFAULT '',
    issue_date INT(11)     NOT NULL DEFAULT 0,
    nfekey     CHAR(60) NOT NULL DEFAULT '',
    PRIMARY KEY (invno),
    UNIQUE (nfekey)
);


SHOW
CREATE TABLE sqldados.iprd;

CREATE TABLE `iprd`
(
    `invno`             INT(10)     NOT NULL DEFAULT '0',
    `qtty`              INT(10)     NOT NULL DEFAULT '0',
    `fob`               BIGINT(15)  NOT NULL DEFAULT '0',
    `cost`              BIGINT(15)  NOT NULL DEFAULT '0',
    `date`              INT(10)     NOT NULL DEFAULT '0',
    `ipi`               INT(10)     NOT NULL DEFAULT '0',
    `auxLong1`          INT(10)     NOT NULL DEFAULT '0',
    `auxLong2`          INT(10)     NOT NULL DEFAULT '0',
    `frete`             INT(10)     NOT NULL DEFAULT '0',
    `seguro`            INT(10)     NOT NULL DEFAULT '0',
    `despesas`          INT(10)     NOT NULL DEFAULT '0',
    `freteIpi`          INT(10)     NOT NULL DEFAULT '0',
    `qttyRessar`        INT(10)     NOT NULL DEFAULT '0',
    `baseIcmsSubst`     BIGINT(15)  NOT NULL DEFAULT '0',
    `icmsSubst`         BIGINT(15)  NOT NULL DEFAULT '0',
    `icms`              BIGINT(15)  NOT NULL DEFAULT '0',
    `discount`          BIGINT(15)  NOT NULL DEFAULT '0',
    `fob4`              BIGINT(15)  NOT NULL DEFAULT '0',
    `cost4`             BIGINT(15)  NOT NULL DEFAULT '0',
    `icmsAliq`          INT(10)     NOT NULL DEFAULT '0',
    `cfop`              INT(10)     NOT NULL DEFAULT '0',
    `auxLong3`          INT(10)     NOT NULL DEFAULT '0',
    `auxLong4`          INT(10)     NOT NULL DEFAULT '0',
    `auxLong5`          INT(10)     NOT NULL DEFAULT '0',
    `auxMy1`            BIGINT(15)  NOT NULL DEFAULT '0',
    `auxMy2`            BIGINT(15)  NOT NULL DEFAULT '0',
    `auxMy3`            BIGINT(15)  NOT NULL DEFAULT '0',
    `baseIcms`          BIGINT(15)  NOT NULL,
    `baseIpi`           BIGINT(15)  NOT NULL,
    `ipiAmt`            BIGINT(15)  NOT NULL,
    `reducaoBaseIcms`   BIGINT(15)  NOT NULL,
    `amtCredIcmsSN`     BIGINT(15)  NOT NULL DEFAULT '0',
    `amtFcpSt`          BIGINT(15)  NOT NULL DEFAULT '0',
    `amtFcpStRet`       BIGINT(15)  NOT NULL DEFAULT '0',
    `amtFcpUfDest`      BIGINT(15)  NOT NULL DEFAULT '0',
    `amtIcmsDeson`      BIGINT(15)  NOT NULL DEFAULT '0',
    `amtIcmsDifer`      BIGINT(15)  NOT NULL DEFAULT '0',
    `amtIcmsEfet`       BIGINT(15)  NOT NULL DEFAULT '0',
    `amtIof`            BIGINT(15)  NOT NULL DEFAULT '0',
    `amtIssQN`          BIGINT(15)  NOT NULL DEFAULT '0',
    `amtIssRet`         BIGINT(15)  NOT NULL DEFAULT '0',
    `amtSubstDest`      BIGINT(15)  NOT NULL DEFAULT '0',
    `amtSubstRetRemet`  BIGINT(15)  NOT NULL DEFAULT '0',
    `baseFcp`           BIGINT(15)  NOT NULL DEFAULT '0',
    `baseFcpSt`         BIGINT(15)  NOT NULL DEFAULT '0',
    `baseFcpStRet`      BIGINT(15)  NOT NULL DEFAULT '0',
    `baseFcpUfDest`     BIGINT(15)  NOT NULL DEFAULT '0',
    `baseIcmsEfet`      BIGINT(15)  NOT NULL DEFAULT '0',
    `baseII`            BIGINT(15)  NOT NULL DEFAULT '0',
    `baseIssQN`         BIGINT(15)  NOT NULL DEFAULT '0',
    `baseSubstDest`     BIGINT(15)  NOT NULL DEFAULT '0',
    `baseSubstRetRemet` BIGINT(15)  NOT NULL DEFAULT '0',
    `deducoes`          BIGINT(15)  NOT NULL DEFAULT '0',
    `outrasRet`         BIGINT(15)  NOT NULL DEFAULT '0',
    `lucroTributado`    INT(10)     NOT NULL,
    `aliqFcp`           INT(10)     NOT NULL DEFAULT '0',
    `aliqFcpSt`         INT(10)     NOT NULL DEFAULT '0',
    `aliqFcpStRet`      INT(10)     NOT NULL DEFAULT '0',
    `aliqFcpUfDest`     INT(10)     NOT NULL DEFAULT '0',
    `aliqIcmsDifer`     INT(10)     NOT NULL DEFAULT '0',
    `aliqIcmsEfet`      INT(10)     NOT NULL DEFAULT '0',
    `aliqIcmsInter`     INT(10)     NOT NULL DEFAULT '0',
    `aliqIcmsPart`      INT(10)     NOT NULL DEFAULT '0',
    `aliqIcmsUfDest`    INT(10)     NOT NULL DEFAULT '0',
    `aliqIssQN`         INT(10)     NOT NULL DEFAULT '0',
    `motIcmsDeson`      INT(10)     NOT NULL DEFAULT '0',
    `percBaseOper`      INT(10)     NOT NULL DEFAULT '0',
    `percCredSN`        INT(10)     NOT NULL DEFAULT '0',
    `percRedIcmsEfet`   INT(10)     NOT NULL DEFAULT '0',
    `percRedIcmsSt`     INT(10)     NOT NULL DEFAULT '0',
    `dfob` DOUBLE NOT NULL DEFAULT '0',
    `l1`                INT(10)     NOT NULL,
    `l2`                INT(10)     NOT NULL,
    `l3`                INT(10)     NOT NULL,
    `l4`                INT(10)     NOT NULL,
    `l5`                INT(10)     NOT NULL,
    `l6`                INT(10)     NOT NULL,
    `l7`                INT(10)     NOT NULL,
    `l8`                INT(10)     NOT NULL,
    `l9`                INT(10)     NOT NULL DEFAULT '0',
    `l10`               INT(10)     NOT NULL DEFAULT '0',
    `l11`               INT(10)     NOT NULL DEFAULT '0',
    `l12`               INT(10)     NOT NULL DEFAULT '0',
    `l13`               INT(10)     NOT NULL DEFAULT '0',
    `l14`               INT(10)     NOT NULL DEFAULT '0',
    `l15`               INT(10)     NOT NULL DEFAULT '0',
    `l16`               INT(10)     NOT NULL DEFAULT '0',
    `l17`               INT(10)     NOT NULL DEFAULT '0',
    `l18`               INT(10)     NOT NULL DEFAULT '0',
    `l19`               INT(10)     NOT NULL DEFAULT '0',
    `l20`               INT(10)     NOT NULL DEFAULT '0',
    `l21`               INT(10)     NOT NULL DEFAULT '0',
    `l22`               INT(10)     NOT NULL DEFAULT '0',
    `l23`               INT(10)     NOT NULL DEFAULT '0',
    `l24`               INT(10)     NOT NULL DEFAULT '0',
    `l25`               INT(10)     NOT NULL DEFAULT '0',
    `l26`               INT(10)     NOT NULL DEFAULT '0',
    `l27`               INT(10)     NOT NULL DEFAULT '0',
    `l28`               INT(10)     NOT NULL DEFAULT '0',
    `m1`                BIGINT(15)  NOT NULL,
    `m2`                BIGINT(15)  NOT NULL,
    `m3`                BIGINT(15)  NOT NULL,
    `m4`                BIGINT(15)  NOT NULL,
    `m5`                BIGINT(15)  NOT NULL,
    `m6`                BIGINT(15)  NOT NULL,
    `m7`                BIGINT(15)  NOT NULL,
    `m8`                BIGINT(15)  NOT NULL,
    `m9`                BIGINT(15)  NOT NULL DEFAULT '0',
    `m10`               BIGINT(15)  NOT NULL DEFAULT '0',
    `m11`               BIGINT(15)  NOT NULL DEFAULT '0',
    `m12`               BIGINT(15)  NOT NULL DEFAULT '0',
    `m13`               BIGINT(15)  NOT NULL DEFAULT '0',
    `m14`               BIGINT(15)  NOT NULL DEFAULT '0',
    `m15`               BIGINT(15)  NOT NULL DEFAULT '0',
    `m16`               BIGINT(15)  NOT NULL DEFAULT '0',
    `m17`               BIGINT(15)  NOT NULL DEFAULT '0',
    `m18`               BIGINT(15)  NOT NULL DEFAULT '0',
    `m19`               BIGINT(15)  NOT NULL DEFAULT '0',
    `m20`               BIGINT(15)  NOT NULL DEFAULT '0',
    `m21`               BIGINT(15)  NOT NULL DEFAULT '0',
    `m22`               BIGINT(15)  NOT NULL DEFAULT '0',
    `m23`               BIGINT(15)  NOT NULL DEFAULT '0',
    `m24`               BIGINT(15)  NOT NULL DEFAULT '0',
    `m25`               BIGINT(15)  NOT NULL DEFAULT '0',
    `m26`               BIGINT(15)  NOT NULL DEFAULT '0',
    `m27`               BIGINT(15)  NOT NULL DEFAULT '0',
    `m28`               BIGINT(15)  NOT NULL DEFAULT '0',
    `d1` DOUBLE NOT NULL DEFAULT '0',
    `d2` DOUBLE NOT NULL DEFAULT '0',
    `d3` DOUBLE NOT NULL DEFAULT '0',
    `d4` DOUBLE NOT NULL DEFAULT '0',
    `d5` DOUBLE NOT NULL DEFAULT '0',
    `d6` DOUBLE NOT NULL DEFAULT '0',
    `d7` DOUBLE NOT NULL DEFAULT '0',
    `d8` DOUBLE NOT NULL DEFAULT '0',
    `d9` DOUBLE NOT NULL DEFAULT '0',
    `d10` DOUBLE NOT NULL DEFAULT '0',
    `d11` DOUBLE NOT NULL DEFAULT '0',
    `d12` DOUBLE NOT NULL DEFAULT '0',
    `d13` DOUBLE NOT NULL DEFAULT '0',
    `d14` DOUBLE NOT NULL DEFAULT '0',
    `d15` DOUBLE NOT NULL DEFAULT '0',
    `d16` DOUBLE NOT NULL DEFAULT '0',
    `d17` DOUBLE NOT NULL DEFAULT '0',
    `d18` DOUBLE NOT NULL DEFAULT '0',
    `d19` DOUBLE NOT NULL DEFAULT '0',
    `d20` DOUBLE NOT NULL DEFAULT '0',
    `storeno`           SMALLINT(5) NOT NULL DEFAULT '0',
    `bits`              SMALLINT(5) NOT NULL DEFAULT '0',
    `auxShort1`         SMALLINT(5) NOT NULL DEFAULT '0',
    `auxShort2`         SMALLINT(5) NOT NULL DEFAULT '0',
    `taxtype`           SMALLINT(5) NOT NULL DEFAULT '0',
    `auxShort3`         SMALLINT(5) NOT NULL DEFAULT '0',
    `auxShort4`         SMALLINT(5) NOT NULL DEFAULT '0',
    `auxShort5`         SMALLINT(5) NOT NULL DEFAULT '0',
    `seqno`             SMALLINT(5) NOT NULL,
    `bits2`             SMALLINT(5) NOT NULL,
    `bits3`             SMALLINT(5) NOT NULL,
    `bits4`             SMALLINT(5) NOT NULL,
    `s1`                SMALLINT(5) NOT NULL,
    `s2`                SMALLINT(5) NOT NULL,
    `s3`                SMALLINT(5) NOT NULL,
    `s4`                SMALLINT(5) NOT NULL,
    `s5`                SMALLINT(5) NOT NULL,
    `s6`                SMALLINT(5) NOT NULL,
    `s7`                SMALLINT(5) NOT NULL,
    `s8`                SMALLINT(5) NOT NULL,
    `s9`                SMALLINT(5) NOT NULL DEFAULT '0',
    `s10`               SMALLINT(5) NOT NULL DEFAULT '0',
    `s11`               SMALLINT(5) NOT NULL DEFAULT '0',
    `s12`               SMALLINT(5) NOT NULL DEFAULT '0',
    `s13`               SMALLINT(5) NOT NULL DEFAULT '0',
    `s14`               SMALLINT(5) NOT NULL DEFAULT '0',
    `s15`               SMALLINT(5) NOT NULL DEFAULT '0',
    `s16`               SMALLINT(5) NOT NULL DEFAULT '0',
    `s17`               SMALLINT(5) NOT NULL DEFAULT '0',
    `s18`               SMALLINT(5) NOT NULL DEFAULT '0',
    `s19`               SMALLINT(5) NOT NULL DEFAULT '0',
    `s20`               SMALLINT(5) NOT NULL DEFAULT '0',
    `s21`               SMALLINT(5) NOT NULL DEFAULT '0',
    `s22`               SMALLINT(5) NOT NULL DEFAULT '0',
    `s23`               SMALLINT(5) NOT NULL DEFAULT '0',
    `s24`               SMALLINT(5) NOT NULL DEFAULT '0',
    `s25`               SMALLINT(5) NOT NULL DEFAULT '0',
    `s26`               SMALLINT(5) NOT NULL DEFAULT '0',
    `s27`               SMALLINT(5) NOT NULL DEFAULT '0',
    `s28`               SMALLINT(5) NOT NULL DEFAULT '0',
    `prdno`             CHAR(16) NOT NULL DEFAULT '',
    `grade`             CHAR(8)  NOT NULL DEFAULT '',
    `auxChar`           CHAR(20) NOT NULL DEFAULT '',
    `auxChar2`          CHAR(20) NOT NULL DEFAULT '',
    `cstIcms`           CHAR(4)  NOT NULL,
    `cstIpi`            CHAR(4)  NOT NULL,
    `c1`                CHAR(40) NOT NULL,
    `c2`                CHAR(40) NOT NULL DEFAULT '',
    `c3`                CHAR(40) NOT NULL DEFAULT '',
    `c4`                CHAR(40) NOT NULL DEFAULT '',
    `c5`                CHAR(40) NOT NULL DEFAULT '',
    `c6`                CHAR(40) NOT NULL DEFAULT '',
    `c7`                CHAR(40) NOT NULL DEFAULT '',
    `c8`                CHAR(40) NOT NULL DEFAULT '',
    `c9`                CHAR(40) NOT NULL DEFAULT '',
    `c10`               CHAR(40) NOT NULL DEFAULT '',
    PRIMARY KEY (`invno`, `prdno`, `grade`, `fob`),
    KEY                 `i2` (`prdno`, `grade`, `date`, `storeno`),
    KEY                 `i3` (`prdno`, `grade`, `storeno`, `date`),
    KEY                 `i4` (`storeno`, `prdno`, `date`),
    KEY                 `i5` (`prdno`, `date`, `storeno`, `grade`),
    KEY                 `i6` (`storeno`, `date`),
    KEY                 `i7` (`invno`, `s1`, `prdno`, `grade`)
) ENGINE = InnoDB
  DEFAULT CHARSET = latin1;

SHOW
CREATE TABLE sqldados.inv;

CREATE TABLE `inv`
(
    `invno`        INT(11)     NOT NULL AUTO_INCREMENT,
    `vendno`       INT(10)     NOT NULL,
    `ordno`        INT(10)     NOT NULL DEFAULT '0',
    `xfrno`        INT(10)     NOT NULL DEFAULT '0',
    `issue_date`   INT(10)     NOT NULL DEFAULT '0',
    `date`         INT(10)     NOT NULL DEFAULT '0',
    `comp_date`    INT(10)     NOT NULL DEFAULT '0',
    `ipi`          BIGINT(15)  NOT NULL DEFAULT '0',
    `icm`          BIGINT(15)  NOT NULL DEFAULT '0',
    `freight`      BIGINT(15)  NOT NULL DEFAULT '0',
    `netamt`       BIGINT(15)  NOT NULL DEFAULT '0',
    `grossamt`     BIGINT(15)  NOT NULL DEFAULT '0',
    `subst_trib`   BIGINT(15)  NOT NULL DEFAULT '0',
    `discount`     BIGINT(15)  NOT NULL DEFAULT '0',
    `prdamt`       BIGINT(15)  NOT NULL DEFAULT '0',
    `despesas`     BIGINT(15)  NOT NULL DEFAULT '0',
    `base_ipi`     BIGINT(15)  NOT NULL DEFAULT '0',
    `aliq`         INT(10)     NOT NULL DEFAULT '0',
    `cfo`          INT(10)     NOT NULL DEFAULT '0',
    `nfNfno`       INT(10)     NOT NULL DEFAULT '0',
    `auxLong1`     INT(10)     NOT NULL DEFAULT '0',
    `auxLong2`     INT(10)     NOT NULL DEFAULT '0',
    `auxMoney1`    BIGINT(15)  NOT NULL DEFAULT '0',
    `auxMoney2`    BIGINT(15)  NOT NULL DEFAULT '0',
    `dataSaida`    INT(10)     NOT NULL DEFAULT '0',
    `amtServicos`  BIGINT(15)  NOT NULL DEFAULT '0',
    `amtIRRF`      BIGINT(15)  NOT NULL DEFAULT '0',
    `amtINSS`      BIGINT(15)  NOT NULL DEFAULT '0',
    `amtISS`       BIGINT(15)  NOT NULL DEFAULT '0',
    `auxMoney3`    BIGINT(15)  NOT NULL DEFAULT '0',
    `auxMoney4`    BIGINT(15)  NOT NULL DEFAULT '0',
    `auxMoney5`    BIGINT(15)  NOT NULL DEFAULT '0',
    `auxLong3`     INT(10)     NOT NULL DEFAULT '0',
    `auxLong4`     INT(10)     NOT NULL DEFAULT '0',
    `auxLong5`     INT(10)     NOT NULL DEFAULT '0',
    `auxLong6`     INT(10)     NOT NULL DEFAULT '0',
    `auxLong7`     INT(10)     NOT NULL DEFAULT '0',
    `auxLong8`     INT(10)     NOT NULL DEFAULT '0',
    `auxLong9`     INT(10)     NOT NULL DEFAULT '0',
    `auxLong10`    INT(10)     NOT NULL DEFAULT '0',
    `auxLong11`    INT(10)     NOT NULL DEFAULT '0',
    `auxLong12`    INT(10)     NOT NULL DEFAULT '0',
    `auxMoney6`    BIGINT(15)  NOT NULL DEFAULT '0',
    `auxMoney7`    BIGINT(15)  NOT NULL DEFAULT '0',
    `auxMoney8`    BIGINT(15)  NOT NULL DEFAULT '0',
    `auxMoney9`    BIGINT(15)  NOT NULL DEFAULT '0',
    `auxMoney10`   BIGINT(15)  NOT NULL DEFAULT '0',
    `auxMoney11`   BIGINT(15)  NOT NULL DEFAULT '0',
    `auxMoney12`   BIGINT(15)  NOT NULL DEFAULT '0',
    `auxMoney13`   BIGINT(15)  NOT NULL DEFAULT '0',
    `icmsUfRemet`  BIGINT(15)  NOT NULL DEFAULT '0',
    `fcp`          BIGINT(15)  NOT NULL DEFAULT '0',
    `fcpSt`        BIGINT(15)  NOT NULL DEFAULT '0',
    `fcpStRet`     BIGINT(15)  NOT NULL DEFAULT '0',
    `servico`      BIGINT(15)  NOT NULL DEFAULT '0',
    `baseIss`      BIGINT(15)  NOT NULL DEFAULT '0',
    `deducoes`     BIGINT(15)  NOT NULL DEFAULT '0',
    `retencoes`    BIGINT(15)  NOT NULL DEFAULT '0',
    `impImport`    BIGINT(15)  NOT NULL DEFAULT '0',
    `issRetido`    BIGINT(15)  NOT NULL DEFAULT '0',
    `l1`           INT(10)     NOT NULL,
    `l2`           INT(10)     NOT NULL,
    `l3`           INT(10)     NOT NULL,
    `l4`           INT(10)     NOT NULL,
    `l5`           INT(10)     NOT NULL,
    `l6`           INT(10)     NOT NULL,
    `l7`           INT(10)     NOT NULL,
    `l8`           INT(10)     NOT NULL,
    `l9`           INT(10)     NOT NULL DEFAULT '0',
    `l10`          INT(10)     NOT NULL DEFAULT '0',
    `l11`          INT(10)     NOT NULL DEFAULT '0',
    `l12`          INT(10)     NOT NULL DEFAULT '0',
    `l13`          INT(10)     NOT NULL DEFAULT '0',
    `l14`          INT(10)     NOT NULL DEFAULT '0',
    `l15`          INT(10)     NOT NULL DEFAULT '0',
    `l16`          INT(10)     NOT NULL DEFAULT '0',
    `l17`          INT(10)     NOT NULL DEFAULT '0',
    `l18`          INT(10)     NOT NULL DEFAULT '0',
    `l19`          INT(10)     NOT NULL DEFAULT '0',
    `l20`          INT(10)     NOT NULL DEFAULT '0',
    `l21`          INT(10)     NOT NULL DEFAULT '0',
    `l22`          INT(10)     NOT NULL DEFAULT '0',
    `l23`          INT(10)     NOT NULL DEFAULT '0',
    `l24`          INT(10)     NOT NULL DEFAULT '0',
    `l25`          INT(10)     NOT NULL DEFAULT '0',
    `l26`          INT(10)     NOT NULL DEFAULT '0',
    `l27`          INT(10)     NOT NULL DEFAULT '0',
    `l28`          INT(10)     NOT NULL DEFAULT '0',
    `m1`           BIGINT(15)  NOT NULL,
    `m2`           BIGINT(15)  NOT NULL,
    `m3`           BIGINT(15)  NOT NULL,
    `m4`           BIGINT(15)  NOT NULL,
    `m5`           BIGINT(15)  NOT NULL,
    `m6`           BIGINT(15)  NOT NULL,
    `m7`           BIGINT(15)  NOT NULL,
    `m8`           BIGINT(15)  NOT NULL,
    `m9`           BIGINT(15)  NOT NULL DEFAULT '0',
    `m10`          BIGINT(15)  NOT NULL DEFAULT '0',
    `m11`          BIGINT(15)  NOT NULL DEFAULT '0',
    `m12`          BIGINT(15)  NOT NULL DEFAULT '0',
    `m13`          BIGINT(15)  NOT NULL DEFAULT '0',
    `m14`          BIGINT(15)  NOT NULL DEFAULT '0',
    `m15`          BIGINT(15)  NOT NULL DEFAULT '0',
    `m16`          BIGINT(15)  NOT NULL DEFAULT '0',
    `m17`          BIGINT(15)  NOT NULL DEFAULT '0',
    `m18`          BIGINT(15)  NOT NULL DEFAULT '0',
    `m19`          BIGINT(15)  NOT NULL DEFAULT '0',
    `m20`          BIGINT(15)  NOT NULL DEFAULT '0',
    `m21`          BIGINT(15)  NOT NULL DEFAULT '0',
    `m22`          BIGINT(15)  NOT NULL DEFAULT '0',
    `m23`          BIGINT(15)  NOT NULL DEFAULT '0',
    `m24`          BIGINT(15)  NOT NULL DEFAULT '0',
    `m25`          BIGINT(15)  NOT NULL DEFAULT '0',
    `m26`          BIGINT(15)  NOT NULL DEFAULT '0',
    `m27`          BIGINT(15)  NOT NULL DEFAULT '0',
    `m28`          BIGINT(15)  NOT NULL DEFAULT '0',
    `weight` DOUBLE DEFAULT NULL,
    `carrno`       SMALLINT(5) NOT NULL DEFAULT '0',
    `packages`     SMALLINT(5) NOT NULL DEFAULT '0',
    `storeno`      SMALLINT(5) NOT NULL DEFAULT '0',
    `indxno`       SMALLINT(5) NOT NULL DEFAULT '0',
    `book_bits`    SMALLINT(5) NOT NULL DEFAULT '0',
    `type`         SMALLINT(5) NOT NULL DEFAULT '0',
    `usernoFirst`  SMALLINT(5) NOT NULL DEFAULT '0',
    `usernoLast`   SMALLINT(5) NOT NULL DEFAULT '0',
    `nfStoreno`    SMALLINT(5) NOT NULL DEFAULT '0',
    `bits`         SMALLINT(5) NOT NULL DEFAULT '0',
    `padbyte`      SMALLINT(5) NOT NULL DEFAULT '0',
    `auxShort1`    SMALLINT(5) NOT NULL DEFAULT '0',
    `auxShort2`    SMALLINT(5) NOT NULL DEFAULT '0',
    `auxShort3`    SMALLINT(5) NOT NULL DEFAULT '0',
    `auxShort4`    SMALLINT(5) NOT NULL DEFAULT '0',
    `auxShort5`    SMALLINT(5) NOT NULL DEFAULT '0',
    `auxShort6`    SMALLINT(5) NOT NULL DEFAULT '0',
    `auxShort7`    SMALLINT(5) NOT NULL DEFAULT '0',
    `auxShort8`    SMALLINT(5) NOT NULL DEFAULT '0',
    `auxShort9`    SMALLINT(5) NOT NULL DEFAULT '0',
    `auxShort10`   SMALLINT(5) NOT NULL DEFAULT '0',
    `auxShort11`   SMALLINT(5) NOT NULL DEFAULT '0',
    `auxShort12`   SMALLINT(5) NOT NULL DEFAULT '0',
    `auxShort13`   SMALLINT(5) NOT NULL DEFAULT '0',
    `auxShort14`   SMALLINT(5) NOT NULL DEFAULT '0',
    `bits2`        SMALLINT(5) NOT NULL,
    `bits3`        SMALLINT(5) NOT NULL,
    `bits4`        SMALLINT(5) NOT NULL,
    `bits5`        SMALLINT(5) NOT NULL DEFAULT '0',
    `s1`           SMALLINT(5) NOT NULL,
    `s2`           SMALLINT(5) NOT NULL,
    `s3`           SMALLINT(5) NOT NULL,
    `s4`           SMALLINT(5) NOT NULL,
    `s5`           SMALLINT(5) NOT NULL,
    `s6`           SMALLINT(5) NOT NULL,
    `s7`           SMALLINT(5) NOT NULL,
    `s8`           SMALLINT(5) NOT NULL,
    `s9`           SMALLINT(5) NOT NULL DEFAULT '0',
    `s10`          SMALLINT(5) NOT NULL DEFAULT '0',
    `s11`          SMALLINT(5) NOT NULL DEFAULT '0',
    `s12`          SMALLINT(5) NOT NULL DEFAULT '0',
    `s13`          SMALLINT(5) NOT NULL DEFAULT '0',
    `s14`          SMALLINT(5) NOT NULL DEFAULT '0',
    `s15`          SMALLINT(5) NOT NULL DEFAULT '0',
    `s16`          SMALLINT(5) NOT NULL DEFAULT '0',
    `s17`          SMALLINT(5) NOT NULL DEFAULT '0',
    `s18`          SMALLINT(5) NOT NULL DEFAULT '0',
    `s19`          SMALLINT(5) NOT NULL DEFAULT '0',
    `s20`          SMALLINT(5) NOT NULL DEFAULT '0',
    `s21`          SMALLINT(5) NOT NULL DEFAULT '0',
    `s22`          SMALLINT(5) NOT NULL DEFAULT '0',
    `s23`          SMALLINT(5) NOT NULL DEFAULT '0',
    `s24`          SMALLINT(5) NOT NULL DEFAULT '0',
    `s25`          SMALLINT(5) NOT NULL DEFAULT '0',
    `s26`          SMALLINT(5) NOT NULL DEFAULT '0',
    `s27`          SMALLINT(5) NOT NULL DEFAULT '0',
    `s28`          SMALLINT(5) NOT NULL DEFAULT '0',
    `nfname`       CHAR(32) NOT NULL DEFAULT '',
    `invse`        CHAR(4)  NOT NULL DEFAULT '',
    `account`      CHAR(16) NOT NULL DEFAULT '',
    `remarks`      CHAR(80) NOT NULL DEFAULT '',
    `contaCredito` CHAR(16) NOT NULL DEFAULT '',
    `contaDebito`  CHAR(16) NOT NULL DEFAULT '',
    `nfNfse`       CHAR(2)  NOT NULL DEFAULT '',
    `auxStr1`      CHAR(20) NOT NULL DEFAULT '',
    `auxStr2`      CHAR(20) NOT NULL DEFAULT '',
    `auxStr3`      CHAR(20) NOT NULL DEFAULT '',
    `auxStr4`      CHAR(20) NOT NULL DEFAULT '',
    `auxStr5`      CHAR(20) NOT NULL DEFAULT '',
    `auxStr6`      CHAR(20) NOT NULL DEFAULT '',
    `c1`           CHAR(40) NOT NULL,
    `c2`           CHAR(40) NOT NULL,
    `c3`           CHAR(40) NOT NULL DEFAULT '',
    `c4`           CHAR(40) NOT NULL DEFAULT '',
    `c5`           CHAR(40) NOT NULL DEFAULT '',
    `c6`           CHAR(40) NOT NULL DEFAULT '',
    `c7`           CHAR(40) NOT NULL DEFAULT '',
    `c8`           CHAR(40) NOT NULL DEFAULT '',
    `c9`           CHAR(40) NOT NULL DEFAULT '',
    `c10`          CHAR(40) NOT NULL DEFAULT '',
    PRIMARY KEY (`invno`),
    KEY            `i3` (`account`),
    KEY            `i4` (`carrno`),
    KEY            `i5` (`ordno`),
    KEY            `i6` (`storeno`, `invse`, `date`),
    KEY            `i7` (`storeno`, `date`),
    KEY            `i8` (`storeno`, `cfo`, `date`),
    KEY            `i9` (`storeno`, `comp_date`),
    KEY            `i10` (`storeno`, `nfname`, `invse`),
    KEY            `i11` (`storeno`, `invno`),
    KEY            `i12` (`auxLong7`, `nfname`, `invse`),
    KEY            `i13` (`vendno`, `date`),
    KEY            `i14` (`auxShort14`),
    KEY            `i15` (`storeno`, `vendno`),
    KEY            `i16` (`auxShort1`, `auxShort2`, `auxLong1`),
    KEY            `i17` (`nfNfno`, `nfStoreno`, `nfNfse`),
    KEY            `i18` (`auxLong3`),
    KEY            `i19` (`storeno`, `account`),
    KEY            `i20` (`l6`, `invno`),
    KEY            `i21` (`storeno`, `vendno`, `nfname`),
    KEY            `i22` (`storeno`, `vendno`, `date`),
    KEY            `i23` (`l8`),
    KEY            `i2` (`vendno`, `nfname`, `invse`, `invno`),
    KEY            `e1` (`invno`, `storeno`, `type`),
    KEY            `i24` (`vendno`, `issue_date`)
) ENGINE = InnoDB
  AUTO_INCREMENT = 856034
  DEFAULT CHARSET = latin1;



SELECT N.storeno AS loja,
       X.invno AS ni,
       CAST(CONCAT(N.nfname, '/', N.invse) AS CHAR) AS nota,
       CAST(TRIM(P.no) AS CHAR) AS codigo,
       IFNULL(X.grade, '') AS grade,
       TRIM(IFNULL(B.barcode, P.barcode)) AS barcode,
       TRIM(MID(P.name, 1, 37)) AS descricao,
       P.mfno AS vendno,
       IFNULL(F.auxChar1, '') AS fornecedor,
       P.typeno AS typeno,
       IFNULL(T.name, '') AS typeName,
       CAST(LPAD(P.clno, 6, '0') AS CHAR) AS clno,
       IFNULL(cl.name, '') AS clname,
       P.m6 AS altura,
       P.m4 AS comprimento,
       P.m5 AS largura,
       P.sp / 100 AS precoCheio,
       IFNULL(S.ncm, '') AS ncm,
       X.qtty / 1000 AS quantidade,
       X.fob / 100 AS preco,
       (X.qtty / 1000) * (X.fob / 100) AS total,
       X.s27 AS marca,
       CAST(MID(IFNULL(L.localizacao, ''), 1, 4) AS CHAR) AS localizacao
FROM sqldados.prd AS P
         INNER JOIN sqldados.iprdConferencia AS X
                    ON P.no = X.prdno
         INNER JOIN sqldados.invConferencia AS N
                    USING (nfekey)
         LEFT JOIN sqldados.prdbar AS B
                   ON P.no = B.prdno AND B.grade = X.grade
         LEFT JOIN sqldados.prdloc AS L
                   ON L.prdno = P.no AND L.storeno = 4
         LEFT JOIN sqldados.vend AS F
                   ON F.no = P.mfno
         LEFT JOIN sqldados.type AS T
                   ON T.no = P.typeno
         LEFT JOIN sqldados.cl
                   ON cl.no = P.clno
         LEFT JOIN sqldados.spedprd AS S
                   ON P.no = S.prdno
WHERE X.invno = :ni
  AND (X.s27 = :marca OR :marca = 0)
GROUP BY codigo, grade;

###########################################

DESCRIBE sqldados.invConferencia;

SELECT *
FROM sqldados.invConferencia;

ALTER TABLE sqldados.invConferencia
    CHANGE issue_date date INT (11) NOT NULL DEFAULT 0;

ALTER TABLE sqldados.invConferencia
    ADD COLUMN marca INT(11) DEFAULT 0;
