package br.com.astrosoft.produto.model.nfeXml

import java.math.BigDecimal

interface IItensNotaReport {
  val tituloRelatorio: String
  val nomeEmitente: String
  val enderecoEmitente: String
  val bairroEmitente: String
  val cepEmitente: String
  val cidadeEmitente: String
  val ufEmitente: String
  val telefoneEmitente: String
  val entradaSaida: String
  val numeroNota: String
  val serieNota: String
  val chaveAcesso: String
  val natureza: String
  val protocolo: String
  val ieEmitente: String
  val ieSubstTrib: String
  val cpnjEmitente: String
  val nomeDestinatario: String
  val cnpjCpfDestinatario: String
  val dataEmissao: String
  val enderecoDestinatario: String
  val bairroDestinatario: String
  val cepDestinatario: String
  val dataSaida: String
  val cidadeDestinatario: String
  val ufDestinatario: String
  val telefoneDestinatario: String
  val ieDestinatario: String
  val horaSaida: String
  val faturaDuplicata: String
  val bcICMS: BigDecimal
  val vlICMS: BigDecimal
  val bcICMSSt: BigDecimal
  val valorICMSSt: BigDecimal
  val vlProdutos: BigDecimal
  val vlFrete: BigDecimal
  val vlSeguro: BigDecimal
  val vlDesconto: BigDecimal
  val vlOutrasDesp: BigDecimal
  val vlIPI: BigDecimal
  val vlTrib: BigDecimal
  val vlNota: BigDecimal
  val nomeTransportadora: String
  val fretePorConta: String
  val codigoANTT: String
  val nfo: String
  val placaVeiculo: String
  val ufVeiculo: String
  val cnpjCPF: String
  val enderecoTransportadora: String
  val cidadeTransportadora: String
  val ufTransportadora: String
  val ieTransportadora: String
  val quantidade: Long
  val especie: String
  val marca: String
  val numeracao: String
  val pesoBruto: BigDecimal
  val pesoLiquido: BigDecimal
  val codigo: String
  val descricao: String
  val codigoBarras: String
  val ncm: String
  val cst: String
  val cfop: String
  val unidade: String
  val quantProduto: BigDecimal
  val valorUnitProduto: BigDecimal
  val valorTotalProduto: BigDecimal
  val bcICMSProduto: BigDecimal
  val vlICMSProduto: BigDecimal
  val vlIPIProduto: BigDecimal
  val aliqICMSProduto: BigDecimal
  val aliqIPIProduto: BigDecimal
  val inscricaoMunicial: String
  val valorServicos: BigDecimal
  val bcISSQN: BigDecimal
  val valorISSQN: BigDecimal
  val informacoesComplementares: String
}